version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: edam15!k2Mp_
      MYSQL_DATABASE: newdb
      MYSQL_PASSWORD: edam15!k2Mp_
    #  ports:
    #    - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  web:
    image: tomcat:latest
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    environment:
      JDBC_URL: jdbc:mysql://db:3306/newdb?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: root
      JDBC_PASS: edam15!k2Mp_
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    links:
      - db
