version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: edam15!k2Mp_
      MYSQL_DATABASE: newdb
      MYSQL_PASSWORD: edam15!k2Mp_
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  web:
    image: tomcat:latest
    environment:
      JDBC_URL: jdbc:mysql://db:3306/newdb?connectTimeout=0&socketTimeout=0&autoReconnect=true
      JDBC_USER: root
      JDBC_PASS: edam15!k2Mp_
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - mynetwork
    command: >
          sh -c "apt-get update && apt-get install -y mysql-client && catalina.sh run"

networks:
  mynetwork:
    driver: bridge
